name: AoC2023-Haskell
version: 1.0
copyright: Massimo Pavoni 2023
author: Massimo Pavoni
github: massimopavoni/AoC2023-Haskell

executables:
  AoC2023-Haskell:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall -Werror -O2 -threaded

dependencies:
  - base
  - array
  - bytestring
  - containers
  - extra
  - ghc
  - matrix
  - megaparsec
  - ordered-containers
  - parallel
  - safe
  - search-algorithms
  - split
  - unordered-containers
  - vector
